import dotenv from 'dotenv';
import { MongoClient } from 'mongodb';

dotenv.config();

const realProducts = [
  {
    id: '101',
    name: 'Mochi Donuts (12 pcs)',
    category: 'dessert',
    price: 40.88,
    description: 'Assorted mochi donuts with chewy texture and unique flavors.',
    imageUrl: '/images/products/mochi-donuts-box.jpg',
    inStock: true,
    ingredients: 'Glutinous rice flour, sugar, whole milk, butter, assorted glazes',
    allergens: 'Dairy, Wheat, Eggs',
    calories: 250,
    flavorProfile: 'Sweet, chewy, and rich',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '102',
    name: 'Mini Kroffle',
    category: 'pastry',
    price: 4.5,
    description: 'Mini croissant waffle with crispy outside and soft inside.',
    imageUrl: '/images/products/mini-kroffle.jpg',
    inStock: true,
    ingredients: 'Croissant dough, pearl sugar, butter',
    allergens: 'Dairy, Wheat',
    calories: 320,
    flavorProfile: 'Buttery, caramelized, and crispy',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '103',
    name: 'Sea Salt French Cream Thai Tea',
    category: 'drink',
    price: 8.04,
    description: 'Classic Thai tea topped with sea salt cream foam.',
    imageUrl: '/images/products/thai-tea.jpg',
    inStock: true,
    ingredients: 'Black tea blend, star anise, sweetened condensed milk, sea salt, heavy cream',
    allergens: 'Dairy',
    calories: 280,
    flavorProfile: 'Sweet, earthy, with a salty-creamy finish',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '104',
    name: 'Crispy Egg Rolls',
    category: 'dessert',
    price: 3.44,
    description: 'Crispy sweet egg rolls with a light texture.',
    imageUrl: '/images/products/crispy-egg-rolls.jpg',
    inStock: true,
    ingredients: 'Wheat flour, eggs, sugar, coconut milk',
    allergens: 'Wheat, Eggs',
    calories: 180,
    flavorProfile: 'Lightly sweet and crunchy',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '105',
    name: 'Seaweed Pork Floss Egg Roll',
    category: 'savory',
    price: 14.94,
    description: 'Savory egg rolls with seaweed and pork floss.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Wheat flour, eggs, pork floss, dried seaweed, soy sauce',
    allergens: 'Wheat, Eggs, Soy',
    calories: 210,
    flavorProfile: 'Savory, umami, and crispy',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '106',
    name: 'Coconut Egg Rolls',
    category: 'dessert',
    price: 14.94,
    description: 'Sweet crispy egg rolls with rich coconut flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Wheat flour, eggs, coconut cream, sugar, sesame seeds',
    allergens: 'Wheat, Eggs',
    calories: 195,
    flavorProfile: 'Sweet, tropical coconut, and crunchy',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '107',
    name: 'Scallion Pork Floss Cake',
    category: 'savory',
    price: 13.79,
    description: 'Soft chiffon cake topped with pork floss and scallions.',
    imageUrl: '/images/products/scallion-pork-floss-cake.jpg',
    inStock: true,
    ingredients: 'Cake flour, eggs, scallions, dried pork floss, mayonnaise',
    allergens: 'Wheat, Eggs, Soy',
    calories: 410,
    flavorProfile: 'Savory, sweet, and umami',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '108',
    name: 'Tiramisu Cuicuidun',
    category: 'dessert',
    price: 6.32,
    description: 'Crispy donut-style pastry with tiramisu flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, mascarpone, espresso powder, cocoa, sugar',
    allergens: 'Wheat, Dairy, Eggs',
    calories: 380,
    flavorProfile: 'Coffee, chocolate, and creamy sweetness',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '109',
    name: 'Blueberry Cuicuidun',
    category: 'dessert',
    price: 6.32,
    description: 'Sweet and sour blueberry crispy donut.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, blueberry compote, cream cheese, sugar',
    allergens: 'Wheat, Dairy',
    calories: 340,
    flavorProfile: 'Fruity, tart, and sweet',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '110',
    name: 'Mango Cuicuidun',
    category: 'dessert',
    price: 6.32,
    description: 'Crispy pastry with mango flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, mango puree, vanilla cream, sugar',
    allergens: 'Wheat, Dairy',
    calories: 350,
    flavorProfile: 'Tropical, sweet, and fruity',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '111',
    name: 'Original Cuicuidun',
    category: 'dessert',
    price: 5.75,
    description: 'Original crispy pastry with a light buttery flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, European butter, sugar',
    allergens: 'Wheat, Dairy',
    calories: 310,
    flavorProfile: 'Rich buttery and crispy',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '112',
    name: 'Chocolate Cuicuidun',
    category: 'dessert',
    price: 6.32,
    description: 'Crispy pastry filled with rich chocolate flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, dark chocolate ganache, cocoa powder',
    allergens: 'Wheat, Dairy',
    calories: 390,
    flavorProfile: 'Deep chocolate and rich',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '113',
    name: 'Matcha Cuicuidun',
    category: 'dessert',
    price: 6.32,
    description: 'Crispy pastry with earthy matcha flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, matcha green tea powder, white chocolate',
    allergens: 'Wheat, Dairy',
    calories: 360,
    flavorProfile: 'Earthy, slightly bitter, and sweet',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '114',
    name: 'Strawberry Cuicuidun',
    category: 'dessert',
    price: 6.32,
    description: 'Crispy pastry with sweet strawberry flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, strawberry glaze, fresh strawberry chunks',
    allergens: 'Wheat, Dairy',
    calories: 330,
    flavorProfile: 'Sweet berry and crisp',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '115',
    name: 'Custard Cuicuidun',
    category: 'dessert',
    price: 6.32,
    description: 'Crispy pastry with creamy custard filling.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, egg yolks, milk, vanilla bean, sugar',
    allergens: 'Wheat, Dairy, Eggs',
    calories: 370,
    flavorProfile: 'Rich vanilla and creamy',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '116',
    name: 'Ube Cuicuidun',
    category: 'dessert',
    price: 6.32,
    description: 'Crispy pastry flavored with sweet purple yam.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry dough, ube halaya, coconut milk',
    allergens: 'Wheat, Dairy',
    calories: 360,
    flavorProfile: 'Earthy, sweet vanilla-like yam flavor',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '117',
    name: 'Taro Mochi Bread',
    category: 'bread',
    price: 5.95,
    description: 'Soft bread with taro flavor and chewy mochi texture.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Bread flour, taro paste, glutinous rice flour, butter',
    allergens: 'Wheat, Dairy',
    calories: 310,
    flavorProfile: 'Sweet, chewy, and starchy',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '118',
    name: 'Red Bean Bread',
    category: 'bread',
    price: 4.95,
    description: 'Soft bakery bread filled with sweet red bean paste.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Bread flour, sweet azuki bean paste, milk, eggs',
    allergens: 'Wheat, Dairy, Eggs',
    calories: 290,
    flavorProfile: 'Sweet bean and fluffy dough',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '119',
    name: 'Pork Floss Bun',
    category: 'savory',
    price: 5.5,
    description: 'Soft bun topped with savory pork floss.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Bread flour, dried pork floss, sweetened mayonnaise, eggs',
    allergens: 'Wheat, Eggs, Soy',
    calories: 340,
    flavorProfile: 'Savory, sweet, and meaty',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '120',
    name: 'Milk Bread',
    category: 'bread',
    price: 6.25,
    description: 'Fluffy milk bread with a soft and tender texture.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Bread flour, whole milk, heavy cream, yeast, sugar',
    allergens: 'Wheat, Dairy',
    calories: 220,
    flavorProfile: 'Light, sweet milk flavor, incredibly fluffy',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '121',
    name: 'Croissant',
    category: 'pastry',
    price: 4.5,
    description: 'Buttery flaky pastry.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Wheat flour, European butter, yeast, salt',
    allergens: 'Wheat, Dairy',
    calories: 280,
    flavorProfile: 'Rich butter and flaky',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '122',
    name: 'Almond Croissant',
    category: 'pastry',
    price: 5.75,
    description: 'Croissant topped with sliced almonds and sweet filling.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Wheat flour, butter, almond frangipane, sliced almonds',
    allergens: 'Wheat, Dairy, Tree Nuts',
    calories: 420,
    flavorProfile: 'Nutty, sweet, and buttery',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '123',
    name: 'Chocolate Donut',
    category: 'dessert',
    price: 4.25,
    description: 'Soft donut coated with chocolate glaze.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Flour, yeast, milk, dark chocolate, sugar',
    allergens: 'Wheat, Dairy, Eggs',
    calories: 310,
    flavorProfile: 'Classic chocolate sweetness',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '124',
    name: 'Blueberry Muffin',
    category: 'dessert',
    price: 4.75,
    description: 'Classic muffin with sweet blueberries.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Flour, fresh blueberries, butter, sugar, baking powder',
    allergens: 'Wheat, Dairy, Eggs',
    calories: 380,
    flavorProfile: 'Sweet berry and cake-like',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '125',
    name: 'Basque Cheesecake',
    category: 'dessert',
    price: 7.5,
    description: 'Creamy cheesecake with a caramelized top.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Cream cheese, heavy cream, sugar, eggs, vanilla',
    allergens: 'Dairy, Eggs',
    calories: 450,
    flavorProfile: 'Burnt caramel notes with a rich creamy center',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '126',
    name: 'Baguette',
    category: 'bread',
    price: 4.95,
    description: 'Classic crusty French-style bread.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Wheat flour, water, yeast, salt',
    allergens: 'Wheat',
    calories: 150, // Per serving
    flavorProfile: 'Crusty outside, soft airy inside',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '127',
    name: 'Matcha Latte',
    category: 'drink',
    price: 6.95,
    description: 'Smooth latte with rich matcha flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Ceremonial grade matcha, milk, simple syrup',
    allergens: 'Dairy',
    calories: 190,
    flavorProfile: 'Earthy, creamy, and sweet',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '128',
    name: 'Thai Milk Tea',
    category: 'drink',
    price: 6.95,
    description: 'Sweet and creamy Thai-style milk tea.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Thai tea leaves, sweetened condensed milk, evaporated milk',
    allergens: 'Dairy',
    calories: 260,
    flavorProfile: 'Strong brewed tea with rich sweet cream',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '129',
    name: 'Sesame Mochi Bun',
    category: 'bread',
    price: 5.5,
    description: 'Chewy bun with black sesame flavor.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Bread flour, black sesame paste, glutinous rice flour',
    allergens: 'Wheat',
    calories: 320,
    flavorProfile: 'Nutty, earthy sesame with a chewy center',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '130',
    name: 'Egg Tart',
    category: 'dessert',
    price: 3.95,
    description: 'Flaky tart shell with silky egg custard filling.',
    imageUrl: '/images/products/default.jpg',
    inStock: true,
    ingredients: 'Pastry flour, butter, egg yolks, evaporated milk, sugar',
    allergens: 'Wheat, Dairy, Eggs',
    calories: 240,
    flavorProfile: 'Flaky butter crust and sweet custard',
    createdAt: new Date('2025-01-01'),
  },
];

const productNames = [
  'Artisan Bread', 'Layered Cake', 'Fruit Tart', 'Stuffed Bun',
  'Glazed Donut', 'Breakfast Muffin', 'Flaky Pastry', 'Butter Cookie',
  'Savory Sandwich', 'Cinnamon Roll',
];

const categories = ['bread', 'pastry', 'dessert', 'savory', 'drink'];

function randomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomPrice(min = 3, max = 18) {
  return Number((Math.random() * (max - min) + min).toFixed(2));
}

function generateSyntheticProducts(count) {
  const syntheticProducts = [];

  for (let i = 0; i < count; i += 1) {
    const idNumber = 1000 + i;
    const category = randomItem(categories);
    const baseName = randomItem(productNames);

    syntheticProducts.push({
      id: String(idNumber),
      name: `${baseName} (Batch ${i + 1})`,
      category,
      price: randomPrice(),
      description: `A delicious ${category} item baked fresh daily.`,
      imageUrl: '/images/products/default.jpg', // Give them all a default image
      inStock: Math.random() > 0.1, // 90% chance to be in stock
      ingredients: 'Flour, sugar, butter, yeast, salt',
      allergens: 'Wheat, Dairy',
      calories: Math.floor(Math.random() * 300) + 150,
      flavorProfile: 'Classic bakery flavors',
      createdAt: new Date(),
    });
  }

  return syntheticProducts;
}

async function seedProducts() {
  const client = new MongoClient(process.env.MONGODB_URI);

  try {
    await client.connect();
    const db = client.db(process.env.DB_NAME);
    const productsCollection = db.collection('products');

    // Clear existing data
    await productsCollection.deleteMany({});

    // Generate 1000 synthetic + your real ones
    const syntheticProducts = generateSyntheticProducts(1000);
    const allProducts = [...realProducts, ...syntheticProducts];

    await productsCollection.insertMany(allProducts);

    console.log(`Inserted ${allProducts.length} products successfully.`);
    console.log(`Real products: ${realProducts.length}`);
    console.log(`Synthetic products: ${syntheticProducts.length}`);
    console.log(`All schema fields (ingredients, calories, etc.) populated!`);
  } catch (error) {
    console.error('Error seeding products:', error);
  } finally {
    await client.close();
  }
}

seedProducts();